name: Gentoo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Gentoo Docker image
      run: docker build . --file Dockerfile --tag gentoo:$(date +%s)
